-- VHDL Entity tb_kalman.kalman_filter_tb.symbol
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 11:08:42 28/04/2015
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--


entity kalman_filter_tb is
-- Declarations

end kalman_filter_tb ;

--
-- VHDL Architecture tb_kalman.kalman_filter_tb.rtl
--
-- Created:
--          by - Juan Lanchares.UNKNOWN (LANCHARES)
--          at - 11:08:42 28/04/2015
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
use IEEE.std_logic_textio.all;
library STD;
use STD.textio.all;

library kalman_filter;
library tb_kalman;

architecture rtl of kalman_filter_tb is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk          : std_logic;
   signal imsr         : std_logic_vector(15 downto 0);    -- measurement values
   signal q_addr       : std_logic_vector(3 downto 0);     -- address for memory Q
   signal q_data       : std_logic_vector(15 downto 0);    -- data coming from memory Q
   signal r            : std_logic_vector(15 downto 0);
   signal rst          : std_logic;
   signal start        : std_logic;
   signal xpo_data_out : std_logic_vector(15 downto 0);    -- posteriori state data


   -- Component Declarations
   component kalman_filter
   port (
      clk          : in     std_logic ;
      imsr         : in     std_logic_vector (15 downto 0); -- measurement values
      q_data       : in     std_logic_vector (15 downto 0); -- data coming from memory Q
      r            : in     std_logic_vector (15 downto 0);
      rst          : in     std_logic ;
      start        : in     std_logic ;
      q_addr       : out    std_logic_vector (3 downto 0);  -- address for memory Q
      xpo_data_out : out    std_logic_vector (15 downto 0)  -- posteriori state data
   );
   end component;
   component kalman_filter_tester
   generic (
      archivo_entrada : string := "T:\TFG2015\src\tb_design\tb_common\text\tb_entrada_kalman_filter.txt";
      archivo_salida  : string := "T:\TFG2015\src\tb_design\tb_common\text\tb_salida_kalman_filter.txt"
   );
   port (
      clk          : in     std_logic ;
      q_addr       : in     std_logic_vector (3 downto 0);
      rst          : in     std_logic ;
      xpo_data_out : in     std_logic_vector (15 downto 0);
      imsr         : out    std_logic_vector (15 downto 0);
      q_data       : out    std_logic_vector (15 downto 0);
      r            : out    std_logic_vector (15 downto 0);
      start        : out    std_logic 
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : kalman_filter use entity kalman_filter.kalman_filter;
   for all : kalman_filter_tester use entity tb_kalman.kalman_filter_tester;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 9 clk
   p_clk : process
   begin
     clk <= '0';
     wait for 5 ns;
     clk <= '1';
     wait for 5 ns;
   end process p_clk;                                      
   
   

   -- HDL Embedded Text Block 10 data
   p_rst : process
   begin
     --wait for 10 ns;
     rst <= '1';
     wait for 10 ns;
     rst <= '0';
     --wait for 10 ns;  
     --r<="0000000000000011";
     --imsr<="0000000000000101";
     --wait for 10 ns;
     --start<='1';
     --wait for 10 ns;
     --start<='0';
     wait;
   end process p_rst; 
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   


   -- Instance port mappings.
   i_kalman_filter : kalman_filter
      port map (
         clk          => clk,
         imsr         => imsr,
         q_data       => q_data,
         r            => r,
         rst          => rst,
         start        => start,
         q_addr       => q_addr,
         xpo_data_out => xpo_data_out
      );
   U_1 : kalman_filter_tester
      generic map (
         archivo_entrada => "T:\TFG2015\src\tb_design\tb_common\text\tb_entrada_kalman_filter.txt",
         archivo_salida  => "T:\TFG2015\src\tb_design\tb_common\text\tb_salida_kalman_filter.txt"
      )
      port map (
         clk          => clk,
         q_addr       => q_addr,
         rst          => rst,
         xpo_data_out => xpo_data_out,
         imsr         => imsr,
         q_data       => q_data,
         r            => r,
         start        => start
      );

end rtl;
